// Dummy data for the marketing UI — used when the backend is down or when
// previewing the design. Shape mirrors what the API returns.

import type {
  Campaign,
  Influencer,
  Niche,
  Notification,
  Order,
  Package,
  Payout,
  PayoutSummary,
  PlatformStats,
  SupportTicket,
  User,
} from './types';

export const DUMMY_NICHES: Niche[] = [
  { id: 'n-1', slug: 'beauty', name: 'Beauty & Skincare' },
  { id: 'n-2', slug: 'fashion', name: 'Fashion' },
  { id: 'n-3', slug: 'fitness', name: 'Fitness' },
  { id: 'n-4', slug: 'food', name: 'Food & Beverage' },
  { id: 'n-5', slug: 'lifestyle', name: 'Lifestyle' },
  { id: 'n-6', slug: 'tech', name: 'Tech & Gadgets' },
  { id: 'n-7', slug: 'travel', name: 'Travel' },
  { id: 'n-8', slug: 'parenting', name: 'Parenting' },
  { id: 'n-9', slug: 'health', name: 'Health & Wellness' },
  { id: 'n-10', slug: 'finance', name: 'Finance' },
  { id: 'n-11', slug: 'education', name: 'Education' },
  { id: 'n-12', slug: 'gaming', name: 'Gaming' },
];

const NICHE_BY_SLUG: Record<string, Niche> = Object.fromEntries(
  DUMMY_NICHES.map((n) => [n.slug, n]),
);

// =============================================================================
// Catalog packs — Nano only.
// Stepped ladder: each pack includes everything from the previous tier plus
// one new deliverable type.
//   Starter → adds nothing (baseline: Reel + Story)
//   Growth  → + UTM Link
//   Booster → + Video Drive Link
//   Viral   → + Performance Report
// All packs include "Content Rights" as a flat benefit.
// =============================================================================
export const DUMMY_PACKAGES: Package[] = [
  {
    id: 'pkg-starter',
    slug: 'starter-pack',
    packName: 'Starter Pack',
    title: 'Starter Pack — 50 Nano Creators',
    description: 'Best for micro-campaigns.',
    subtitle: 'Best for micro-campaigns.',
    tier: 'NANO',
    deliverables: [
      { type: 'IG_REEL', qty: 1 },
      { type: 'IG_STORY', qty: 1 },
    ],
    influencerCount: 50,
    price: 20000,
    mrp: 25000,
    pricePerInfluencer: 400,
    benefits: ['Content Rights'],
    isMostPopular: false,
    estReach: 250000,
    estEngagement: 18000,
    isActive: true,
    createdAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'pkg-growth',
    slug: 'growth-plan',
    packName: 'Growth Plan',
    title: 'Growth Plan — 100 Nano Creators',
    description: 'Scale outreach with performance add-ons.',
    subtitle: 'Scale outreach with performance add-ons.',
    tier: 'NANO',
    deliverables: [
      { type: 'IG_REEL', qty: 1 },
      { type: 'IG_STORY', qty: 1 },
      { type: 'UTM_LINK', qty: 1 },
    ],
    influencerCount: 100,
    price: 30000,
    mrp: 35000,
    pricePerInfluencer: 300,
    benefits: ['Content Rights'],
    isMostPopular: true,
    estReach: 500000,
    estEngagement: 36000,
    isActive: true,
    createdAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'pkg-booster',
    slug: 'brand-booster',
    packName: 'Brand Booster',
    title: 'Brand Booster — 250 Nano Creators',
    description: 'For aggressive expansion.',
    subtitle: 'For aggressive expansion.',
    tier: 'NANO',
    deliverables: [
      { type: 'IG_REEL', qty: 1 },
      { type: 'IG_STORY', qty: 1 },
      { type: 'UTM_LINK', qty: 1 },
      { type: 'VIDEO_DRIVE_LINK', qty: 1 },
    ],
    influencerCount: 250,
    price: 62500,
    mrp: 75000,
    pricePerInfluencer: 250,
    benefits: ['Content Rights'],
    isMostPopular: false,
    estReach: 1250000,
    estEngagement: 90000,
    isActive: true,
    createdAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'pkg-viral',
    slug: 'viral-pro',
    packName: 'Viral Pro',
    title: 'Viral Pro — 500 Nano Creators',
    description: 'High-volume advanced rights.',
    subtitle: 'High-volume advanced rights.',
    tier: 'NANO',
    deliverables: [
      { type: 'IG_REEL', qty: 1 },
      { type: 'IG_STORY', qty: 1 },
      { type: 'UTM_LINK', qty: 1 },
      { type: 'VIDEO_DRIVE_LINK', qty: 1 },
      { type: 'PERFORMANCE_REPORT', qty: 1 },
    ],
    influencerCount: 500,
    price: 100000,
    mrp: 125000,
    pricePerInfluencer: 200,
    benefits: ['Content Rights'],
    isMostPopular: false,
    estReach: 2500000,
    estEngagement: 180000,
    isActive: true,
    createdAt: '2026-05-01T10:00:00Z',
  },
];

export const DUMMY_INFLUENCERS: Influencer[] = [
  {
    id: 'inf-1',
    user: { id: 'u-1', fullName: 'Aanya Mehta', avatarUrl: null },
    bio: 'Beauty + skincare creator from Mumbai. Honest reviews only.',
    city: 'Mumbai',
    state: 'Maharashtra',
    tier: 'MICRO',
    totalFollowers: 47000,
    avgEngagementRate: 4.7,
    isAvailable: true,
    socialAccounts: [
      { platform: 'INSTAGRAM', handle: 'aanyamehta', followers: 47000, engagementRate: 4.7, profileUrl: '#', isVerified: true },
      { platform: 'YOUTUBE', handle: 'AanyaBeauty', followers: 12000, engagementRate: 2.1, profileUrl: '#', isVerified: true },
    ],
    niches: [{ niche: NICHE_BY_SLUG.beauty }, { niche: NICHE_BY_SLUG.lifestyle }],
    rateCards: [
      { id: 'rc-1', deliverable: 'IG_REEL', price: 8500 },
      { id: 'rc-2', deliverable: 'IG_POST', price: 5000 },
      { id: 'rc-3', deliverable: 'IG_STORY', price: 2000 },
    ],
    badge: 'TOP_RATED',
    completedCampaigns: 24,
    successRate: 94,
    responseRate: 98,
    avgRating: 4.8,
    totalEarnings: 184000,
  },
  {
    id: 'inf-2',
    user: { id: 'u-2', fullName: 'Rohan Iyer', avatarUrl: null },
    bio: 'Lifestyle + tech reviews. Based in Bangalore.',
    city: 'Bangalore',
    state: 'Karnataka',
    tier: 'MICRO',
    totalFollowers: 62000,
    avgEngagementRate: 5.2,
    isAvailable: true,
    socialAccounts: [
      { platform: 'INSTAGRAM', handle: 'rohaniyer', followers: 62000, engagementRate: 5.2, profileUrl: '#', isVerified: true },
    ],
    niches: [{ niche: NICHE_BY_SLUG.lifestyle }, { niche: NICHE_BY_SLUG.tech }],
    rateCards: [
      { id: 'rc-4', deliverable: 'IG_REEL', price: 10000 },
      { id: 'rc-5', deliverable: 'IG_STORY', price: 2500 },
    ],
    badge: 'RISING_TALENT',
    completedCampaigns: 6,
    successRate: 88,
    responseRate: 92,
    avgRating: 4.6,
    totalEarnings: 42000,
  },
  {
    id: 'inf-3',
    user: { id: 'u-3', fullName: 'Priya Sharma', avatarUrl: null },
    bio: 'Fitness & nutrition coach. Trained 100+ clients.',
    city: 'Delhi',
    state: 'Delhi',
    tier: 'MACRO',
    totalFollowers: 240000,
    avgEngagementRate: 3.8,
    isAvailable: true,
    socialAccounts: [
      { platform: 'INSTAGRAM', handle: 'priyafit', followers: 240000, engagementRate: 3.8, profileUrl: '#', isVerified: true },
      { platform: 'YOUTUBE', handle: 'PriyaFit', followers: 85000, engagementRate: 2.9, profileUrl: '#', isVerified: true },
    ],
    niches: [{ niche: NICHE_BY_SLUG.fitness }, { niche: NICHE_BY_SLUG.health }],
    rateCards: [
      { id: 'rc-6', deliverable: 'IG_REEL', price: 35000 },
      { id: 'rc-7', deliverable: 'YT_VIDEO', price: 80000 },
    ],
    badge: 'TOP_RATED_PLUS',
    completedCampaigns: 58,
    successRate: 97,
    responseRate: 95,
    avgRating: 4.9,
    totalEarnings: 920000,
  },
  {
    id: 'inf-4',
    user: { id: 'u-4', fullName: 'Vikram Singh', avatarUrl: null },
    bio: 'Street food explorer. Vlogger across 18 cities.',
    city: 'Indore',
    state: 'Madhya Pradesh',
    tier: 'MICRO',
    totalFollowers: 85000,
    avgEngagementRate: 6.1,
    isAvailable: true,
    socialAccounts: [
      { platform: 'INSTAGRAM', handle: 'vikramfoodie', followers: 85000, engagementRate: 6.1, profileUrl: '#', isVerified: true },
    ],
    niches: [{ niche: NICHE_BY_SLUG.food }, { niche: NICHE_BY_SLUG.travel }],
    rateCards: [
      { id: 'rc-8', deliverable: 'IG_REEL', price: 12000 },
      { id: 'rc-9', deliverable: 'STORE_VISIT', price: 18000 },
    ],
    badge: 'TOP_RATED',
    completedCampaigns: 19,
    successRate: 93,
    responseRate: 97,
    avgRating: 4.7,
    totalEarnings: 240000,
  },
  {
    id: 'inf-5',
    user: { id: 'u-5', fullName: 'Naina Kapoor', avatarUrl: null },
    bio: 'Parenting + kids fashion. Mom of two.',
    city: 'Pune',
    state: 'Maharashtra',
    tier: 'NANO',
    totalFollowers: 8500,
    avgEngagementRate: 7.4,
    isAvailable: true,
    socialAccounts: [
      { platform: 'INSTAGRAM', handle: 'naina_mom', followers: 8500, engagementRate: 7.4, profileUrl: '#', isVerified: true },
    ],
    niches: [{ niche: NICHE_BY_SLUG.parenting }, { niche: NICHE_BY_SLUG.fashion }],
    rateCards: [
      { id: 'rc-10', deliverable: 'IG_REEL', price: 3500 },
      { id: 'rc-11', deliverable: 'IG_POST', price: 2000 },
    ],
    badge: 'RISING_TALENT',
    completedCampaigns: 3,
    successRate: 100,
    responseRate: 100,
    avgRating: 4.9,
    totalEarnings: 12500,
  },
  {
    id: 'inf-6',
    user: { id: 'u-6', fullName: 'Karan Desai', avatarUrl: null },
    bio: 'Gaming + tech YouTuber. PC builds, reviews, esports.',
    city: 'Hyderabad',
    state: 'Telangana',
    tier: 'MACRO',
    totalFollowers: 420000,
    avgEngagementRate: 4.5,
    isAvailable: true,
    socialAccounts: [
      { platform: 'YOUTUBE', handle: 'KaranGames', followers: 420000, engagementRate: 4.5, profileUrl: '#', isVerified: true },
      { platform: 'INSTAGRAM', handle: 'karan_games', followers: 120000, engagementRate: 3.2, profileUrl: '#', isVerified: true },
    ],
    niches: [{ niche: NICHE_BY_SLUG.gaming }, { niche: NICHE_BY_SLUG.tech }],
    rateCards: [
      { id: 'rc-12', deliverable: 'YT_VIDEO', price: 120000 },
      { id: 'rc-13', deliverable: 'YT_SHORT', price: 25000 },
    ],
    badge: 'EXPERT_VETTED',
    completedCampaigns: 120,
    successRate: 98,
    responseRate: 96,
    avgRating: 5.0,
    totalEarnings: 4800000,
  },
];

export const DUMMY_BRANDS: string[] = [
  'NOVA',
  'SUTRA',
  'BLOOM',
  'PLUM',
  'VITA',
  'ZEN',
  'ATLAS',
  'AURA',
  'KAVI',
  'LUMEN',
  'SAGE',
  'OLIVE',
];

export function dummyOrEmpty<T>(value: T | null | undefined, dummy: T): T {
  if (!value) return dummy;
  if (Array.isArray(value) && value.length === 0) return dummy;
  return value;
}

// =============================================================================
// Demo dashboard data — used in demo mode when the backend isn't running.
// =============================================================================

export const DUMMY_ADMIN_USER: User = {
  id: 'demo-admin-1',
  email: 'admin@collabhype.in',
  fullName: 'Riya Verma',
  role: 'ADMIN',
  phone: null,
  avatarUrl: null,
  isActive: true,
  emailVerified: true,
  phoneVerified: false,
  createdAt: '2026-01-01T10:00:00Z',
};

export const DUMMY_PLATFORM_STATS: PlatformStats = {
  totalUsers: 1247,
  totalBrands: 184,
  totalCreators: 1063,
  activeCampaigns: 38,
  gmv30d: 4_872_500,
  signupsThisWeek: 47,
  pendingApprovals: 12,
  payoutsQueued: 23,
};

export const DUMMY_ADMIN_USERS_LIST: Array<Pick<User, 'id' | 'fullName' | 'email' | 'role' | 'isActive' | 'createdAt'>> = [
  { id: 'u-a-1', fullName: 'Aanya Mehta', email: 'aanya@example.com', role: 'INFLUENCER', isActive: true, createdAt: '2026-05-10T10:00:00Z' },
  { id: 'u-a-2', fullName: 'Acme Brand', email: 'hello@acme.com', role: 'BRAND', isActive: true, createdAt: '2026-05-09T10:00:00Z' },
  { id: 'u-a-3', fullName: 'Rohan Iyer', email: 'rohan@example.com', role: 'INFLUENCER', isActive: true, createdAt: '2026-05-08T10:00:00Z' },
  { id: 'u-a-4', fullName: 'Bloom Skincare', email: 'team@bloom.com', role: 'BRAND', isActive: true, createdAt: '2026-05-07T10:00:00Z' },
  { id: 'u-a-5', fullName: 'Priya Sharma', email: 'priya@example.com', role: 'INFLUENCER', isActive: true, createdAt: '2026-05-06T10:00:00Z' },
  { id: 'u-a-6', fullName: 'Karan Desai', email: 'karan@example.com', role: 'INFLUENCER', isActive: false, createdAt: '2026-05-05T10:00:00Z' },
];

export const DUMMY_BRAND_USER: User = {
  id: 'demo-brand-1',
  email: 'demo@brand.com',
  fullName: 'Acme Brand',
  role: 'BRAND',
  phone: '+919812345678',
  avatarUrl: null,
  isActive: true,
  emailVerified: true,
  phoneVerified: true,
  createdAt: '2026-04-01T10:00:00Z',
  brandProfile: {
    id: 'bp-demo',
    userId: 'demo-brand-1',
    companyName: 'Acme Brand',
    website: 'https://acme.example.com',
    industry: 'Beauty & Skincare',
    gstin: '',
    logoUrl: '',
    about: 'A demo brand running influencer campaigns on Collabhype.',
  },
};

export const DUMMY_INFLUENCER_USER: User = {
  id: 'demo-inf-1',
  email: 'demo@creator.com',
  fullName: 'Aanya Mehta',
  role: 'INFLUENCER',
  phone: '+919812345679',
  avatarUrl: null,
  isActive: true,
  emailVerified: true,
  phoneVerified: false,
  createdAt: '2026-03-15T10:00:00Z',
  influencerProfile: {
    id: 'inf-demo',
    userId: 'demo-inf-1',
    bio: 'Beauty + skincare creator from Mumbai. Honest reviews only.',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'IN',
    languages: 'en,hi',
    gender: 'female',
    dob: '1996-04-15T00:00:00Z',
    tier: 'MICRO',
    totalFollowers: 59000,
    avgEngagementRate: 4.4,
    isAvailable: true,
    baseRate: 8500,
    upiId: 'demo@upi',
    socialAccounts: [
      {
        id: 'sa-demo-1',
        platform: 'INSTAGRAM',
        handle: 'aanyamehta',
        profileUrl: 'https://instagram.com/aanyamehta',
        followers: 47000,
        following: 320,
        posts: 280,
        avgLikes: 1900,
        avgComments: 60,
        engagementRate: 4.7,
        isVerified: true,
        lastSyncedAt: '2026-05-10T10:00:00Z',
      },
      {
        id: 'sa-demo-2',
        platform: 'YOUTUBE',
        handle: 'AanyaBeauty',
        profileUrl: 'https://youtube.com/@AanyaBeauty',
        followers: 12000,
        posts: 42,
        engagementRate: 2.1,
        isVerified: true,
        lastSyncedAt: '2026-05-10T10:00:00Z',
      },
    ],
    niches: [
      { influencerId: 'inf-demo', nicheId: 'n-1', niche: NICHE_BY_SLUG.beauty },
      { influencerId: 'inf-demo', nicheId: 'n-5', niche: NICHE_BY_SLUG.lifestyle },
    ],
    rateCards: [
      { id: 'rc-demo-1', deliverable: 'IG_REEL', price: 8500 },
      { id: 'rc-demo-2', deliverable: 'IG_POST', price: 5000 },
      { id: 'rc-demo-3', deliverable: 'IG_STORY', price: 2000 },
      { id: 'rc-demo-4', deliverable: 'YT_VIDEO', price: 35000 },
    ],
  },
};

export const DUMMY_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'CH-XKLM-A1B2',
    brandUserId: 'demo-brand-1',
    subtotal: 75000,
    tax: 0,
    total: 75000,
    currency: 'INR',
    status: 'IN_PROGRESS',
    paidAt: '2026-05-08T14:30:00Z',
    createdAt: '2026-05-08T14:25:00Z',
    items: [
      {
        id: 'oi-1',
        itemType: 'PACKAGE',
        snapshot: {
          packageTitle: 'Growth Pack — 5 Micro Fashion Influencers',
          deliverables: [
            { type: 'IG_REEL', qty: 1 },
            { type: 'IG_STORY', qty: 2 },
          ],
        },
        price: 75000,
        qty: 1,
      },
    ],
    _count: { campaigns: 1 },
  },
  {
    id: 'ord-2',
    orderNumber: 'CH-WJPM-Z9X8',
    brandUserId: 'demo-brand-1',
    subtotal: 25000,
    tax: 0,
    total: 25000,
    currency: 'INR',
    status: 'COMPLETED',
    paidAt: '2026-04-22T11:10:00Z',
    createdAt: '2026-04-22T11:00:00Z',
    items: [
      {
        id: 'oi-2',
        itemType: 'PACKAGE',
        snapshot: {
          packageTitle: 'Starter Pack — 10 Nano Beauty Creators',
          deliverables: [
            { type: 'IG_REEL', qty: 1 },
            { type: 'IG_STORY', qty: 1 },
          ],
        },
        price: 25000,
        qty: 1,
      },
    ],
    _count: { campaigns: 1 },
  },
];

export const DUMMY_ORDER_DETAIL: Order & {
  escrows: Array<{ id: string; amount: number; status: string; createdAt: string; releasedAt: string | null }>;
  campaigns: Array<Partial<Campaign>>;
} = {
  ...DUMMY_ORDERS[0],
  escrows: [
    {
      id: 'esc-1',
      amount: 75000,
      status: 'HELD',
      createdAt: '2026-05-08T14:30:00Z',
      releasedAt: null,
    },
  ],
  campaigns: [
    {
      id: 'camp-1',
      title: 'Growth Pack — 5 Micro Fashion Influencers',
      status: 'IN_PROGRESS',
      deliverables: [
        { id: 'd-1', status: 'PAID', deliverable: 'IG_REEL', amountPayable: 8000 },
        { id: 'd-2', status: 'APPROVED', deliverable: 'IG_STORY', amountPayable: 1500 },
        { id: 'd-3', status: 'DRAFT_SUBMITTED', deliverable: 'IG_STORY', amountPayable: 1500 },
      ],
    },
  ],
};

export const DUMMY_CAMPAIGNS_BRAND: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Growth Pack — 5 Micro Fashion Influencers',
    status: 'IN_PROGRESS',
    createdAt: '2026-05-08T14:30:00Z',
    order: {
      id: 'ord-1',
      orderNumber: 'CH-XKLM-A1B2',
      total: 75000,
      status: 'IN_PROGRESS',
      paidAt: '2026-05-08T14:30:00Z',
    },
    _count: { deliverables: 15 },
  },
  {
    id: 'camp-2',
    title: 'Starter Pack — 10 Nano Beauty Creators',
    status: 'COMPLETED',
    createdAt: '2026-04-22T11:00:00Z',
    order: {
      id: 'ord-2',
      orderNumber: 'CH-WJPM-Z9X8',
      total: 25000,
      status: 'COMPLETED',
      paidAt: '2026-04-22T11:10:00Z',
    },
    _count: { deliverables: 20 },
  },
];

export const DUMMY_CAMPAIGNS_INFLUENCER: Campaign[] = [
  {
    id: 'camp-3',
    title: 'Bloom Skincare — Spring launch',
    status: 'IN_PROGRESS',
    createdAt: '2026-05-05T10:00:00Z',
    order: {
      orderNumber: 'CH-LMNO-P3Q4',
      brand: {
        fullName: 'Bloom',
        brandProfile: { companyName: 'Bloom Skincare', logoUrl: null },
      },
    },
    deliverables: [
      { id: 'd-10', deliverable: 'IG_REEL', status: 'DRAFT_SUBMITTED', amountPayable: 8500 },
      { id: 'd-11', deliverable: 'IG_STORY', status: 'PENDING', amountPayable: 2000 },
    ],
  },
  {
    id: 'camp-4',
    title: 'Sutra Foods — Tier-2 vlog',
    status: 'COMPLETED',
    createdAt: '2026-04-10T10:00:00Z',
    order: {
      orderNumber: 'CH-VWXY-R5S6',
      brand: {
        fullName: 'Sutra',
        brandProfile: { companyName: 'Sutra Foods', logoUrl: null },
      },
    },
    deliverables: [
      { id: 'd-20', deliverable: 'IG_REEL', status: 'PAID', amountPayable: 8500 },
    ],
  },
];

export const DUMMY_CAMPAIGN_DETAIL_BRAND: Campaign = {
  id: 'camp-1',
  title: 'Growth Pack — 5 Micro Fashion Influencers',
  brief:
    'Spring collection campaign. Natural lighting, warm tones, lifestyle shots. Tag @acmebrand in the first 3 seconds.',
  hashtags: '#acmespring #acmestyle',
  doList: 'Use the brand handle in the first 3 seconds.\nShow the product fit honestly.',
  dontList: "Don't compare to competitor brands.\nAvoid filters that distort fabric color.",
  startDate: '2026-05-10T00:00:00Z',
  endDate: '2026-05-30T00:00:00Z',
  status: 'IN_PROGRESS',
  createdAt: '2026-05-08T14:30:00Z',
  order: {
    id: 'ord-1',
    orderNumber: 'CH-XKLM-A1B2',
    total: 75000,
    status: 'IN_PROGRESS',
    paidAt: '2026-05-08T14:30:00Z',
  },
  deliverables: [
    {
      id: 'd-1',
      deliverable: 'IG_REEL',
      status: 'DRAFT_SUBMITTED',
      amountPayable: 8000,
      draftUrl: 'https://example.com/draft-1',
      qty: 1,
      influencerId: 'inf-2',
      influencer: DUMMY_INFLUENCERS[1],
    },
    {
      id: 'd-2',
      deliverable: 'IG_REEL',
      status: 'POSTED',
      amountPayable: 8000,
      postedUrl: 'https://instagram.com/p/abc123',
      qty: 1,
      influencerId: 'inf-3',
      influencer: DUMMY_INFLUENCERS[2],
    },
    {
      id: 'd-3',
      deliverable: 'IG_STORY',
      status: 'PAID',
      amountPayable: 1500,
      qty: 1,
      influencerId: 'inf-4',
      influencer: DUMMY_INFLUENCERS[3],
    },
  ],
};

export const DUMMY_CAMPAIGN_DETAIL_INFLUENCER: Campaign = {
  id: 'camp-3',
  title: 'Bloom Skincare — Spring launch',
  brief:
    'Spring skincare routine. 60-second Reel showing the morning routine with our serum + moisturizer.',
  hashtags: '#bloomroutine #springglow',
  doList: 'Mention the brand in the first 5 seconds.\nShow the texture of the product.',
  dontList: "Don't show your own skincare brands in the same video.",
  startDate: '2026-05-10T00:00:00Z',
  endDate: '2026-05-25T00:00:00Z',
  status: 'IN_PROGRESS',
  createdAt: '2026-05-05T10:00:00Z',
  order: {
    orderNumber: 'CH-LMNO-P3Q4',
    brand: {
      fullName: 'Bloom',
      brandProfile: {
        companyName: 'Bloom Skincare',
        logoUrl: null,
        about: 'D2C skincare for sensitive skin.',
      },
    },
  },
  deliverables: [
    {
      id: 'd-10',
      deliverable: 'IG_REEL',
      status: 'DRAFT_SUBMITTED',
      amountPayable: 8500,
      draftUrl: 'https://example.com/draft',
      qty: 1,
      influencerId: 'inf-demo',
    },
    {
      id: 'd-11',
      deliverable: 'IG_STORY',
      status: 'PENDING',
      amountPayable: 2000,
      qty: 1,
      influencerId: 'inf-demo',
    },
  ],
};

export const DUMMY_PAYOUTS: Payout[] = [
  {
    id: 'p-1',
    influencerId: 'inf-demo',
    amount: 8500,
    currency: 'INR',
    status: 'PAID',
    razorpayPayoutId: 'pout_demoXYZ',
    paidAt: '2026-04-22T15:00:00Z',
    createdAt: '2026-04-22T11:30:00Z',
  },
  {
    id: 'p-2',
    influencerId: 'inf-demo',
    amount: 2000,
    currency: 'INR',
    status: 'PENDING',
    razorpayPayoutId: null,
    paidAt: null,
    createdAt: '2026-05-10T09:00:00Z',
  },
  {
    id: 'p-3',
    influencerId: 'inf-demo',
    amount: 5000,
    currency: 'INR',
    status: 'PROCESSING',
    razorpayPayoutId: 'pout_demoABC',
    paidAt: null,
    createdAt: '2026-05-08T10:00:00Z',
  },
];

export const DUMMY_PAYOUT_SUMMARY: PayoutSummary = {
  total: 15500,
  pending: 7000,
  paid: 8500,
  failed: 0,
  currency: 'INR',
};

const MINUTES = 60 * 1000;
const HOURS = 60 * MINUTES;
const DAYS = 24 * HOURS;

export const DUMMY_NOTIFICATIONS: Notification[] = [
  {
    id: 'nt-1',
    type: 'deliverable.draft',
    title: 'New draft to review',
    body: 'Aanya Mehta submitted a draft for "Growth Plan — 100 Nano Creators".',
    link: '/dashboard/campaigns/camp-1',
    isRead: false,
    createdAt: new Date(Date.now() - 12 * MINUTES).toISOString(),
  },
  {
    id: 'nt-2',
    type: 'order.paid',
    title: 'Order CH-XKLM-A1B2 confirmed',
    body: 'Payment of ₹75,000 was received. Campaign briefs dispatched to 5 creators.',
    link: '/dashboard/orders/ord-1',
    isRead: false,
    createdAt: new Date(Date.now() - 45 * MINUTES).toISOString(),
  },
  {
    id: 'nt-3',
    type: 'campaign.assigned',
    title: 'New campaign assigned',
    body: 'You\'ve been booked for "Bloom Skincare — Spring launch". Brief is ready inside.',
    link: '/dashboard/campaigns/camp-3',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * HOURS).toISOString(),
  },
  {
    id: 'nt-4',
    type: 'deliverable.approved',
    title: 'Draft approved',
    body: 'Your Reel for "Bloom Skincare — Spring launch" was approved. Post when ready.',
    link: '/dashboard/campaigns/camp-3',
    isRead: false,
    createdAt: new Date(Date.now() - 3 * HOURS).toISOString(),
  },
  {
    id: 'nt-5',
    type: 'deliverable.revision',
    title: 'Revision requested',
    body: 'Acme Brand asked for tweaks on your IG Story draft — open the campaign to see feedback.',
    link: '/dashboard/campaigns/camp-3',
    isRead: false,
    createdAt: new Date(Date.now() - 5 * HOURS).toISOString(),
  },
  {
    id: 'nt-6',
    type: 'deliverable.posted',
    title: 'Creator posted live',
    body: '@vikramfoodie marked their Reel for "Growth Plan" as posted. Released payment is pending.',
    link: '/dashboard/campaigns/camp-1',
    isRead: true,
    createdAt: new Date(Date.now() - 1 * DAYS).toISOString(),
  },
  {
    id: 'nt-7',
    type: 'deliverable.paid',
    title: 'Payment released',
    body: '₹8,500 released for your IG Reel on "Sutra Foods — Tier-2 vlog". Payout queued to your UPI.',
    link: '/dashboard/payouts',
    isRead: true,
    createdAt: new Date(Date.now() - 1 * DAYS - 4 * HOURS).toISOString(),
  },
  {
    id: 'nt-8',
    type: 'badge.upgraded',
    title: 'Badge upgraded — Top Rated',
    body: 'Congrats! Your stats just crossed the Top Rated threshold. Brands now see your badge.',
    link: '/dashboard/profile',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * DAYS).toISOString(),
  },
  {
    id: 'nt-9',
    type: 'order.completed',
    title: 'Order CH-WJPM-Z9X8 completed',
    body: 'All deliverables paid. Escrow released. Thanks for shipping a great campaign.',
    link: '/dashboard/orders/ord-2',
    isRead: true,
    createdAt: new Date(Date.now() - 3 * DAYS).toISOString(),
  },
  {
    id: 'nt-10',
    type: 'system.welcome',
    title: 'Welcome to Collabhype',
    body: 'Get started — connect your socials, set your rate card, and you\'ll show up in brand searches.',
    link: '/dashboard/socials',
    isRead: true,
    createdAt: new Date(Date.now() - 5 * DAYS).toISOString(),
  },
];

// =============================================================================
// Support / disputes — sample tickets for each role.
// =============================================================================

export const DUMMY_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tk-1',
    ticketNumber: 'CH-T-A1B2-C3D4',
    userId: 'demo-brand-1',
    subject: 'Creator hasn\'t responded to the brief in 5 days',
    category: 'CAMPAIGN',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    orderId: 'ord-1',
    campaignId: 'camp-1',
    deliverableId: null,
    resolution: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    user: {
      id: 'demo-brand-1',
      fullName: 'Acme Brand',
      email: 'demo@brand.com',
      role: 'BRAND',
      avatarUrl: null,
    },
    assignedTo: { id: 'demo-admin-1', fullName: 'Riya Verma', email: 'admin@collabhype.in' },
    order: { id: 'ord-1', orderNumber: 'CH-XKLM-A1B2', total: 75000, status: 'IN_PROGRESS' },
    campaign: { id: 'camp-1', title: 'Growth Plan — 100 Nano Creators', status: 'IN_PROGRESS' },
    deliverable: null,
    _count: { messages: 4 },
  },
  {
    id: 'tk-2',
    ticketNumber: 'CH-T-E5F6-G7H8',
    userId: 'demo-inf-1',
    subject: 'Payout of ₹8,500 still pending after 4 days',
    category: 'PAYOUT',
    priority: 'HIGH',
    status: 'AWAITING_USER',
    orderId: 'ord-2',
    campaignId: 'camp-4',
    deliverableId: null,
    resolution: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    user: {
      id: 'demo-inf-1',
      fullName: 'Aanya Mehta',
      email: 'demo@creator.com',
      role: 'INFLUENCER',
      avatarUrl: null,
    },
    assignedTo: { id: 'demo-admin-1', fullName: 'Riya Verma', email: 'admin@collabhype.in' },
    order: null,
    campaign: { id: 'camp-4', title: 'Sutra Foods — Tier-2 vlog', status: 'COMPLETED' },
    deliverable: null,
    _count: { messages: 3 },
  },
  {
    id: 'tk-3',
    ticketNumber: 'CH-T-I9J0-K1L2',
    userId: 'demo-brand-1',
    subject: 'Dispute: creator posted edited version vs approved draft',
    category: 'DISPUTE',
    priority: 'URGENT',
    status: 'OPEN',
    orderId: 'ord-1',
    campaignId: 'camp-1',
    deliverableId: 'd-2',
    resolution: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    user: {
      id: 'demo-brand-1',
      fullName: 'Acme Brand',
      email: 'demo@brand.com',
      role: 'BRAND',
      avatarUrl: null,
    },
    assignedTo: null,
    order: { id: 'ord-1', orderNumber: 'CH-XKLM-A1B2', total: 75000, status: 'IN_PROGRESS' },
    campaign: { id: 'camp-1', title: 'Growth Plan — 100 Nano Creators', status: 'IN_PROGRESS' },
    deliverable: { id: 'd-2', deliverable: 'IG_REEL', status: 'POSTED', amountPayable: 8000 },
    _count: { messages: 1 },
  },
  {
    id: 'tk-4',
    ticketNumber: 'CH-T-M3N4-O5P6',
    userId: 'demo-brand-1',
    subject: 'Need GST invoice for order CH-WJPM-Z9X8',
    category: 'BILLING',
    priority: 'NORMAL',
    status: 'RESOLVED',
    orderId: 'ord-2',
    campaignId: null,
    deliverableId: null,
    resolution: 'Invoice emailed to billing@acmebrand.com on 9 May.',
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    user: {
      id: 'demo-brand-1',
      fullName: 'Acme Brand',
      email: 'demo@brand.com',
      role: 'BRAND',
      avatarUrl: null,
    },
    assignedTo: { id: 'demo-admin-1', fullName: 'Riya Verma', email: 'admin@collabhype.in' },
    order: { id: 'ord-2', orderNumber: 'CH-WJPM-Z9X8', total: 25000, status: 'COMPLETED' },
    campaign: null,
    deliverable: null,
    _count: { messages: 3 },
  },
  {
    id: 'tk-5',
    ticketNumber: 'CH-T-Q7R8-S9T0',
    userId: 'demo-inf-1',
    subject: 'Instagram OAuth keeps failing on Connect step',
    category: 'TECHNICAL',
    priority: 'NORMAL',
    status: 'OPEN',
    orderId: null,
    campaignId: null,
    deliverableId: null,
    resolution: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    user: {
      id: 'demo-inf-1',
      fullName: 'Aanya Mehta',
      email: 'demo@creator.com',
      role: 'INFLUENCER',
      avatarUrl: null,
    },
    assignedTo: null,
    order: null,
    campaign: null,
    deliverable: null,
    _count: { messages: 1 },
  },
];

export const DUMMY_SUPPORT_MESSAGES: Record<string, import('./types').SupportMessage[]> = {
  'tk-1': [
    {
      id: 'sm-1-1',
      ticketId: 'tk-1',
      authorId: 'demo-brand-1',
      authorRole: 'BRAND',
      body: 'Hi — Aanya Mehta hasn\'t responded to the brief I sent on Monday. Can you nudge?',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      author: { id: 'demo-brand-1', fullName: 'Acme Brand', role: 'BRAND', avatarUrl: null },
    },
    {
      id: 'sm-1-2',
      ticketId: 'tk-1',
      authorId: 'demo-admin-1',
      authorRole: 'ADMIN',
      body: 'Thanks for flagging. We\'ve reached out to Aanya — she replied she\'ll have a draft by Friday EOD.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
      author: { id: 'demo-admin-1', fullName: 'Riya Verma', role: 'ADMIN', avatarUrl: null },
    },
    {
      id: 'sm-1-3',
      ticketId: 'tk-1',
      authorId: 'demo-brand-1',
      authorRole: 'BRAND',
      body: 'Appreciate the quick turnaround. Will wait for Friday.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      author: { id: 'demo-brand-1', fullName: 'Acme Brand', role: 'BRAND', avatarUrl: null },
    },
    {
      id: 'sm-1-4',
      ticketId: 'tk-1',
      authorId: 'demo-admin-1',
      authorRole: 'ADMIN',
      body: 'Draft just landed in your campaign view. Closing this out once you approve.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      author: { id: 'demo-admin-1', fullName: 'Riya Verma', role: 'ADMIN', avatarUrl: null },
    },
  ],
  'tk-2': [
    {
      id: 'sm-2-1',
      ticketId: 'tk-2',
      authorId: 'demo-inf-1',
      authorRole: 'INFLUENCER',
      body: 'My payout of ₹8,500 for Sutra Foods is still showing pending. Was approved 4 days back.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
      author: { id: 'demo-inf-1', fullName: 'Aanya Mehta', role: 'INFLUENCER', avatarUrl: null },
    },
    {
      id: 'sm-2-2',
      ticketId: 'tk-2',
      authorId: 'demo-admin-1',
      authorRole: 'ADMIN',
      body: 'Looking into it. Razorpay shows the payout was initiated but stuck on bank verification. We\'ll need your latest UPI handle to retry.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      author: { id: 'demo-admin-1', fullName: 'Riya Verma', role: 'ADMIN', avatarUrl: null },
    },
  ],
  'tk-3': [
    {
      id: 'sm-3-1',
      ticketId: 'tk-3',
      authorId: 'demo-brand-1',
      authorRole: 'BRAND',
      body: 'The reel posted by Karan Desai is different from the one we approved. He added a competitor mention in the closing 3 seconds. Need this resolved before we release the next payment.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      author: { id: 'demo-brand-1', fullName: 'Acme Brand', role: 'BRAND', avatarUrl: null },
    },
  ],
  'tk-4': [
    {
      id: 'sm-4-1',
      ticketId: 'tk-4',
      authorId: 'demo-brand-1',
      authorRole: 'BRAND',
      body: 'Hi, please share a GST invoice for our completed order.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
      author: { id: 'demo-brand-1', fullName: 'Acme Brand', role: 'BRAND', avatarUrl: null },
    },
    {
      id: 'sm-4-2',
      ticketId: 'tk-4',
      authorId: 'demo-admin-1',
      authorRole: 'ADMIN',
      body: 'Sure — could you confirm your GSTIN and the billing email?',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
      author: { id: 'demo-admin-1', fullName: 'Riya Verma', role: 'ADMIN', avatarUrl: null },
    },
    {
      id: 'sm-4-3',
      ticketId: 'tk-4',
      authorId: 'demo-admin-1',
      authorRole: 'ADMIN',
      body: 'Invoice emailed to billing@acmebrand.com on 9 May. Closing this out — let us know if anything is off.',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      author: { id: 'demo-admin-1', fullName: 'Riya Verma', role: 'ADMIN', avatarUrl: null },
    },
  ],
  'tk-5': [
    {
      id: 'sm-5-1',
      ticketId: 'tk-5',
      authorId: 'demo-inf-1',
      authorRole: 'INFLUENCER',
      body: 'When I tap Connect on Instagram I keep getting "Connection failed". Tried Chrome and Safari on my iPhone.',
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      author: { id: 'demo-inf-1', fullName: 'Aanya Mehta', role: 'INFLUENCER', avatarUrl: null },
    },
  ],
};
